tasks:
  clean:
    cmd: rmdir /s /q build
    exit-codes: [0,2]
  conan-install-debug:
    cmd: conan install . --output-folder=build --build=missing -s build_type=Debug
  conan-install-release:
    cmd: conan install . --output-folder=build --build=missing -s build_type=Release
  cmake-configure:
    depends-on: 
      - conan-install-debug
      - conan-install-release
    work-dir: build
    cmd: cmake .. -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake"
  build-release:
    depends-on: 
      - conan-install-release
      - cmake-configure
    work-dir: build
    cmd: cmake --build . --config Release
    after: open-in-explorer
  build-debug:
    depends-on: 
      - conan-install-debug
      - cmake-configure
    work-dir: build
    cmd: cmake --build . --config Debug
    after: open-in-explorer
  open-in-explorer:
    hidden: true
    work-dir: build
    cmd: explorer ReleaseZip
    exit-codes: [0,1]