# Можно устанавливать значения в формате Inja Templates
# Подробнее об Inja: https://github.com/pantor/inja
# {% set pgsql_home="C:\\Programs\\pgsql" %}
# {% set nginx_home="C:\\Projects\\programs\\nginx" %}
# {% set node="C:\\Programs\\node\\node.exe" %}
# Все объявленные переменные будут доступны через подстановки в формате: ${pgsql_home}, ${nginx_home}, ${node}
services:
  service-name:
    # Название сервиса - опционально.
    # Если name не указан, тогда именем сервиса будет считаться тэг внутри секции services
    name: ServiceName
    
    # По умолчанию используется системная кодировка консоли.
    # Можно включить перекодирование в UTF-8 (это полезно для сервисов, которые нативно работают в UTF-8)
    utf8: true

    # Список зависимостей для сервиса.
    # Утилита будет запускать сервисы из списка dependsOn перед зависимым сервисом.
    depends-on:
      - anotherServiceName
      - oneMoreServiceName
    
    # Рабочая директория для сервиса
    work-dir: "/dir"
    
    # Переменные окружения для сервиса
    env:
      PGPORT: 15433
    
    # Shell команда для запуска сервиса - краткий вариант
    start: bin\pg_ctl start -D data -l postgres.txt

    # Команда запуска - подробный вариант
    start:
      cmd: 
        - bin\pg_ctl start -D data -l postgres.txt
        - echo "Started!"
      work-dir: /dir
      env:
        PGPORT: 15433
      utf8: true
      # Нужно ли отделять процесс в отдельную группу.
      # false - не отделять, будет дочерний процесс от утилиты.
      # true - отделить, будет самостоятельным процессом
      create-new-process-group: true
      # Отсоединиться от процесса через N секунд
      detach-after-seconds: 3
      # Отсоединиться от процесса после получения указанной фразы в STDOUT.
      # Если detach-after-seconds и detach-after-message не указаны, тогда утилита будет ждать полного завершения команды start-команды.
      detach-after-message: Server started
      # Таймаут ожидания команды: N секунд
      timeout: 5.5
      # Какие коды возврата считать успешным выполнением
      exit-codes: [0]

    # Команда остановки - формат тот же, что и start.
    # Если stop-команда не указана, тогда для остановки сервиса утилита будет посылать SIGTERM всем процессам,
    #  подпадающим под фильтр process-filter.
    stop: bin\pg_ctl stop -D data

    stop:
      cmd: 
        - bin\pg_ctl stop -D data
      work-dir: /dir
      utf8: true
      create-new-process-group: false
      detach-after-seconds: 3
      detach-after-message: Server stopped
      timeout: 5.5
      exit-codes: [0]

    # Процесс для мониторинга. Утилита определяет статус сервиса по наличию активного процесса в системе
    process-filter: ${PGSQL_HOME}/bin/postgres.exe

    # Второй способ указать process-filter - с уточнением аргументов командной строки искомого процесса и / или рабочей директории процесса.
    # Все параметры - шаблоны, можно указывать * (означает 0, 1 или множество любых символов) и ? (означает один любой символ).
    process-filter: 
      exe: postgres.exe
      args: "*-D data*"
      workingDirectory: ${PGSQL_HOME}
    # Если не указан process-filter, тогда Утилита не может определить активность сервиса, 
    # и, соответственно, такой сервис становится start-only сервисом (его можно только запустить, но не остановить).

    # Проверка здоровья сервиса
    healthcheck:
      # Команда для проверки.
      cmd: bin\pg_isready -h localhost -d postgres -U postgres
      # Рабочая директория. Если не укащана, наследуется от сервиса
      work-dir: /dir
      # Переменные окружения. Если не указаны, наследуются от сервиса
      env:
        PGPORT: 5432
      # Режим UTF-8. Если не указан, наследуется от сервиса
      utf8: false
      # Ожидаемые коды возврата команды. По умолчанию 0
      exit-codes: [0]
      # Интервал между запусками command в секундах
      interval: 1.5
      # Таймаут для всего healthcheck в секундах
      timeout: 15

tasks:
  hello-world-task:
    # Название задачи - опционально
    name: Print Hello World
    # По умолчанию вывод команд кодируется в UTF-8,
    # Но это можно отключить для некоторых сервисов или команд, и тогда их текст будет выводится в системной локали
    utf8: false
    # Рабочая директория для shell команды
    work-dir: .
    # Переменные окружения для команды
    env:
      HELLO_WORLD: "Hello World"
    # Команда
    cmd: echo %HELLO_WORLD%
    # Таймаут выполнения в секундах
    timeout: 3.75

  mkdir-data:
    # Задачи можно скрывать из списка задач.
    # Например, задачи, которые выполняются только в составе другой задачи.
    hidden: true
    cmd: mkdir ".data"
    # Можно перечислить коды возврата, которые нужно считать успешным выполнением задачи
    exit-codes: [0, 1]

  rm-file:
    hidden: true
    work-dir: .data
    cmd: del file.txt
    exit-codes: [0, 1]
    
  write-file:
    name: "Write file"
    work-dir: .data
    # Список задач, от которых зависит данная задача
    # Утилита будет выполнять указанные задачи перед зависимой задачей
    depends-on:
      - mkdir-data
    # Список задач, которые безусловно запускаются перед данной задачей (даже если уже были запущены ранее)
    before:
      - rm-file
    cmd: echo "Hello World" > file.txt
    # Список задач, которые безусловно запускаются после данной задачи (даже если уже были запущены ранее)
    after:
      - another-task

  # В задаче можно задавать несколько команд.
  # Все команды одной задачи объединятся в &&-цепочку
  chain-task:
    name: Chain Write File
    exit-codes: [0,1]
    cmd:
      - mkdir ".data"
      - del file.txt
      - echo Hello World >> file.txt
