# Можно устанавливать значения в формате Inja Templates
# Подробнее об Inja: https://github.com/pantor/inja
# {% set pgsql_home="C:\\Programs\\pgsql" %}
# {% set nginx_home="C:\\Projects\\programs\\nginx" %}
# {% set node="C:\\Programs\\node\\node.exe" %}
# Все объявленные переменные будут доступны через подстановки в формате: ${pgsql_home}, ${nginx_home}, ${node}
services:
  serviceName:
    # Название сервиса - опционально.
    # Если name не указан, тогда именем сервиса будет считаться тэг внутри секции services
    name: "ServiceName"
    
    # По умолчанию вывод кодируется в UTF-8,
    # Но это можно отключить для некоторых сервисов или команд, и тогда их текст будет выводится в системной локали
    utf8: false

    # Список зависимостей для сервиса.
    # Утилита будет запускать сервисы из списка dependsOn перед зависимым сервисом.
    dependsOn:
      - anotherServiceName
      - oneMoreServiceName
    
    # Рабочая директория для сервиса
    workingDirectory: "/dir"
    
    # Переменные окружения для сервиса
    environment:
      PGPORT: 15433
    
    # Shell команда для запуска сервиса
    startCommand: bin\pg_ctl.exe start -D data -l postgres.txt

    # Отсоединиться от процесса через указанное количество секунд.
    # После отсоединения сервис считается запущенным.
    detachAfterSeconds: 3
    
    # Отсоединиться от процесса после получения указанного сообщения в консоли
    detachAfterMessage: Server started
    # Если detachAfterSeconds и detachAfterMessage не указаны, тогда Утилита будет ждать полного завершения команды startCommand.

    # Процесс для мониторинга. Утилита определяет статус сервиса по наличию активного процесса в системе
    monitorProcess: ${PGSQL_HOME}/bin/postgres.exe

    # Второй способ указать monitorProcess - с уточнением аргументов командной строки искомого процесса.
    # В шаблонах args можно указывать * (означает 0, 1 или множество любых символов) и ? (означает один любой символ).
    monitorProcess: 
      executable: ${TEST_EXE}
      args: "*--flag Something *"
    # Если не указан monitorProcess, тогда Утилита не может определить активность сервиса, 
    # и, соответственно, такой сервис становится start-only сервисом (его можно только запустить, но не остановить).
    
    # Shell команда для остановки сервиса.
    # Если stopCommand не указана, тогда для остановки сервиса Утилита будет посылать SIGTERM всем процессам,
    #  подпадающим под фильтр monitorProcess.
    stopCommand: bin\pg_ctl stop -D data

    # Проверка здоровья сервиса
    healthcheck:
      # Команда для проверки. Наследует workingDirectory и environment от сервиса
      command: bin\pg_isready -h localhost -d postgres -U postgres
      # Рабочая директория. Если не укащана, наследуется от сервиса
      workingDirectory: /dir
      # Переменные окружения. Если не указаны, наследуются от сервиса
      environment:
        PGPORT: 5432
      # Режим UTF-8. Если не указан, наследуется от сервиса
      utf8: false
      # Ожидаемые коды возврата команды. По умолчанию 0
      exitCodes: [0]
      # Интервал между запусками command в секундах
      interval: 1
      # Таймаут для всего healthcheck в секундах
      timeout: 15

tasks:
  helloWorldTask:
    # Название задачи - опционально
    name: Print Hello World
    # По умолчанию вывод команд кодируется в UTF-8,
    # Но это можно отключить для некоторых сервисов или команд, и тогда их текст будет выводится в системной локали
    utf8: false
    # Рабочая директория для shell команды
    workingDirectory: .
    # Переменные окружения для команды
    environment:
      HELLO_WORLD: "Hello World"
    # Команда
    command: echo %HELLO_WORLD%
    # Таймаут выполнения в секундах
    timeout: 3

  mkdir-data:
    # Задачи можно скрывать из списка задач.
    # Например, задачи, которые выполняются только в составе другой задачи.
    hidden: true
    command: mkdir ".data"
    # Можно перечислить коды возврата, которые нужно считать успешным выполнением задачи
    exitCodes: [0, 1]
  rm-file:
    hidden: true
    workingDirectory: .data
    command: del file.txt
    exitCodes: [0, 1]
  write-file:
    name: "Write file"
    workingDirectory: .data
    # Список задач, от которых зависит данная задача
    # Утилита будет выполнять указанные задачи перед зависимой задачей
    dependsOn:
      - mkdir-data
    # Список задач, которые безусловно запускаются перед данной задачей (даже если уже были запущены ранее)
    before:
      - rm-file
    command: echo "Hello World" > file.txt
    # Список задач, которые безусловно запускаются после данной задачи (даже если уже были запущены ранее)
    after:
      - Lua Script

  # В задаче можно задавать несколько команд.
  # Все команды одной задачи объединятся в &&-цепочку
  chain-task:
    name: Chain Write File
    exitCodes: [0,1]
    command:
      - mkdir ".data"
      - del file.txt
      - echo Hello World >> file.txt
